// src/react/Card.tsx
import React from 'react';

export interface CardProps {
    title?: string;
    image?: string;
    interactive?: boolean;
    variant?: 'default' | 'success' | 'warning' | 'error' | 'info';
    size?: 'sm' | 'md' | 'lg';
    children?: React.ReactNode;
}

export const Card: React.FC<CardProps> = ({
    title = '',
    image = '',
    interactive = false,
    variant = 'default',
    size = 'md',
    children
}) => {
    const getSizeClasses = () => {
        switch (size) {
            case 'sm':
                return 'p-3';
            case 'lg':
                return 'p-6';
            default:
                return 'p-4';
        }
    };

    const getVariantClasses = () => {
        switch (variant) {
            case 'success':
                return 'border-green-200 bg-green-50';
            case 'warning':
                return 'border-yellow-200 bg-yellow-50';
            case 'error':
                return 'border-red-200 bg-red-50';
            case 'info':
                return 'border-blue-200 bg-blue-50';
            default:
                return 'border-gray-200 bg-white';
        }
    };

    const cardClasses = [
        'rounded-lg transition-all duration-200',
        'hover:shadow-adaptive-md',
        interactive ? 'cursor-pointer hover:scale-[1.02]' : '',
        getSizeClasses(),
        getVariantClasses(),
    ].join(' ');

    const titleClasses = 'text-lg font-semibold mb-2 text-primary';

    return (
        <div className={cardClasses}>
            {image && (
                <img
                    src={image}
                    alt={title}
                    className="w-full h-48 object-cover rounded-md mb-4"
                />
            )}

            {title && (
                <h3 className={titleClasses}>{title}</h3>
            )}

            {children}
        </div>
    );
};

export default Card;

// src/components/atoms/Card.svelte
<script lang="ts">
    import { getCardVariantClasses } from "../../lib/variant-utils";

    export let title: string = "";
    export let image: string = "";
    export let interactive: boolean = false;
    export let variant: "default" | "success" | "warning" | "error" | "info" =
        "default";
    export let size: "sm" | "md" | "lg" = "md";

    // Size classes
    $: sizeClasses = {
        sm: "p-3",
        md: "p-4",
        lg: "p-6",
    };

    // Get variant class using utility function
    $: variantClass = getCardVariantClasses(variant);

    // Card classes
    $: cardClasses = [
        "rounded-lg transition-all duration-200",
        "hover:shadow-adaptive-md",
        interactive ? "cursor-pointer hover:scale-[1.02]" : "",
        sizeClasses[size],
        variantClass,
    ].join(" ");

    // Title classes using semantic text colors
    $: titleClasses = "text-lg font-semibold mb-2 text-primary";
</script>

<div class={cardClasses}>
    {#if image}
        <img
            src={image}
            alt={title}
            class="w-full h-48 object-cover rounded-md mb-4"
        />
    {/if}

    {#if title}
        <h3 class={titleClasses}>{title}</h3>
    {/if}

    <slot />
</div>
