// src/components/atoms/Input.svelte
<script lang="ts">
    import { generateId } from "../../routes/lib/ssr-safe";

    interface Props {
        value?: string;
        type?: string;
        name?: string;
        label?: string;
        placeholder?: string;
        disabled?: boolean;
        size?: "sm" | "md" | "lg";
        variant?: "default" | "success" | "warning" | "error";
        oninput?: (event: Event) => void;
    }

    let {
        value = "",
        type = "text",
        name = "",
        label = "",
        placeholder = "",
        disabled = false,
        size = "md",
        variant = "default",
        oninput,
        ...restProps
    }: Props = $props();

    // Generate unique ID - SSR safe
    let inputId = $state(generateId("input"));

    // Simple size classes
    let sizeClasses = $derived({
        sm: "px-3 py-1.5 text-sm",
        md: "px-4 py-2 text-sm",
        lg: "px-5 py-3 text-base",
    });

    // Get variant class using utility function
    let variantClass = $derived(() => {
        const variantMap = {
            default:
                "border-gray-300 focus:border-blue-500 focus:ring-blue-500",
            success:
                "border-green-300 focus:border-green-500 focus:ring-green-500",
            warning:
                "border-yellow-300 focus:border-yellow-500 focus:ring-yellow-500",
            error: "border-red-300 focus:border-red-500 focus:ring-red-500",
        };
        return variantMap[variant] || variantMap.default;
    });

    // Input classes
    let inputClasses = $derived(
        [
            "w-full rounded-md transition-colors duration-200",
            "focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-surface",
            "disabled:opacity-50 disabled:cursor-not-allowed disabled:bg-surface-disabled",
            sizeClasses[size],
            variantClass,
        ].join(" "),
    );

    // Label classes using semantic text colors
    let labelClasses = $derived("block text-sm font-medium text-primary mb-1");

    function handleInput(event: Event) {
        const target = event.target as HTMLInputElement;
        value = target.value;

        // Call the parent's oninput handler if provided
        if (oninput) {
            oninput(event);
        }
    }
</script>

<div>
    {#if label}
        <label for={inputId} class={labelClasses}>{label}</label>
    {/if}
    <input
        id={inputId}
        {type}
        {name}
        {value}
        {placeholder}
        {disabled}
        class={inputClasses}
        oninput={handleInput}
        {...restProps}
    />
</div>

// src/react/Input.tsx
import React, { useState, useEffect } from 'react';

export interface InputProps {
    value?: string;
    type?: string;
    name?: string;
    label?: string;
    placeholder?: string;
    disabled?: boolean;
    size?: 'sm' | 'md' | 'lg';
    variant?: 'default' | 'success' | 'warning' | 'error';
    onInput?: (event: React.FormEvent<HTMLInputElement>) => void;
}

export const Input: React.FC<InputProps> = ({
    value = '',
    type = 'text',
    name = '',
    label = '',
    placeholder = '',
    disabled = false,
    size = 'md',
    variant = 'default',
    onInput
}) => {
    const [inputId, setInputId] = useState('');

    useEffect(() => {
        setInputId(`input-${Math.random().toString(36).substr(2, 9)}`);
    }, []);

    const getSizeClasses = () => {
        switch (size) {
            case 'sm':
                return 'px-3 py-1.5 text-sm';
            case 'lg':
                return 'px-5 py-3 text-base';
            default:
                return 'px-4 py-2 text-sm';
        }
    };

    const getVariantClasses = () => {
        switch (variant) {
            case 'success':
                return 'border-green-300 focus:border-green-500 focus:ring-green-500';
            case 'warning':
                return 'border-yellow-300 focus:border-yellow-500 focus:ring-yellow-500';
            case 'error':
                return 'border-red-300 focus:border-red-500 focus:ring-red-500';
            default:
                return 'border-gray-300 focus:border-blue-500 focus:ring-blue-500';
        }
    };

    const inputClasses = [
        'w-full rounded-md transition-colors duration-200',
        'focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-surface',
        'disabled:opacity-50 disabled:cursor-not-allowed disabled:bg-surface-disabled',
        getSizeClasses(),
        getVariantClasses(),
    ].join(' ');

    const labelClasses = 'block text-sm font-medium text-primary mb-1';

    const handleInput = (event: React.FormEvent<HTMLInputElement>) => {
        if (onInput) {
            onInput(event);
        }
    };

    return (
        <div>
            {label && (
                <label htmlFor={inputId} className={labelClasses}>
                    {label}
                </label>
            )}
            <input
                id={inputId}
                type={type}
                name={name}
                value={value}
                placeholder={placeholder}
                disabled={disabled}
                className={inputClasses}
                onInput={handleInput}
            />
        </div>
    );
};

export default Input;
